module.exports = [
  '*.medium.com',
  // custom domains has been deprecated by Medium.com
  // but I'll try to support them since they're still in use by some publications
  'eand.co',
  'theascent.pub',
  // top publications with custom domains
  '500ish.com',
  'android.jlelse.eu',
  'artplusmarketing.com',
  'blog.coinbase.com',
  'blog.discordapp.com',
  'blog.growthhackers.com',
  'blog.markgrowth.com',
  'blog.medium.com',
  'blog.producthunt.com',
  'blog.prototypr.io',
  'blog.qz.com',
  'blog.twitch.tv',
  'brightthemag.com',
  'bullshit.ist',
  'byrslf.co',
  'chatbotsmagazine.com',
  'codeburst.io',
  'entrepreneurshandbook.co',
  'femsplain.com',
  'fityourself.club',
  'hackernoon.com',
  'humanparts.medium.com',
  'insiders.fortune.com',
  'library.gv.com',
  'medium.economist.com',
  'medium.muz.li',
  'psiloveyou.xyz',
  'thecreative.cafe',
  'thinkgrowth.org',
  'timeline.com',
  'towardsdatascience.com',
  'travel.hostfully.com',
  'uxdesign.cc',
  'uxplanet.org',
  'writingcooperative.com'
];
